### ISSUE TITLE
Help with using certain packages

### ISSUE THREAD

**Issue by jawadakhan97** [clearmatics/qreacto#16]
Hi, hope this is not irrelevant, feel free to delete/move this if it is.

I was wondering if with qreacto and jsdelivr I could use the following in a quarto website: 
- https://threejs.org/docs/#manual/en/introduction/Installation
- https://github.com/donmccurdy/three-gltf-viewer

The former seems to have a way to import it in CDN. I am not really all that familiar with web stuff, if you could point me in the right way (ChatGPT was less than helpful) that too would be much appreciated :3

**Comment by dweng0** [comment]
Hi there, there's a good way to test if a package can be used or not:

- Jump onto [esm run](https://www.jsdelivr.com/esm)
- Type in the name of the package then open the jsfiddle:
![image](https://github.com/clearmatics/qreacto/assets/5268627/fc8d4dfb-cecf-4115-aa20-2edb614cacac)
- The fiddle will log out the package
![image](https://github.com/clearmatics/qreacto/assets/5268627/f9c2655a-74ce-4062-a757-9f8863751c9c)
- And if you can see an interface in the console logs, there is a good chance you can use the package:
![image](https://github.com/clearmatics/qreacto/assets/5268627/ea918cea-2576-471a-b3c6-789531b6a331)

In the case of three.js, it can be accessed using the [default](https://jsfiddle.net/5easnhk7/) notation

There are some **GOTCHAS**

- Generally, React packages dont play well with Qreacto. 
- Always test the package, it might be possible to pull the default in. but it _could_ still not work as expected
- A good example of this is D3.js which exposes the default namespace, but a dependency (to do with dates) causes it to crash.
