### ISSUE TITLE
Error running filter /Applications/quarto/share/filters/main.lua:

### ISSUE THREAD

**Issue by jurjoroa** [clearmatics/qreacto#19]
When I execute the example.qmd downloading the entire repo, this message it's showed:

"Error running filter /Applications/quarto/share/filters/main.lua:
...s Locales/GitHub/qreacto/_extensions/qreacto/qreacto.lua:325: attempt to concatenate a nil value (field 'directory')
stack traceback:
	...s Locales/GitHub/qreacto/_extensions/qreacto/qreacto.lua:367: in function <...s Locales/GitHub/qreacto/_extensions/qreacto/qreacto.lua:354>
	(...tail calls...)
	[string "..."]:1789: in function <[string "..."]:1787>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:14235: in function 'transformShortcodeBlocks'
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:449: in local 'callback'
	/Applications/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:495: in function </Applications/quarto/share/filters/main.lua:476>
stack traceback:
	/Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:449: in local 'callback'
	/Applications/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:495: in function </Applications/quarto/share/filters/main.lua:476>"

The quarto version I have is Version: 1.3.450

**Comment by dweng0** [comment]
Hey @jurjoroa did you run preview in the root of the directory? it looks like it had trouble finding resources, could be `_components/` folder was missing? although, the code handles that gracefully.

Have you tried adding it as an extension instead of cloning the repo. (following the quarto docs). and then just copy/paste an example in?
