### ISSUE TITLE
How to add dynamical  content  by Props?

### ISSUE THREAD

**Issue by math4mad** [clearmatics/qreacto#20]
How to add dynamical  content  by Props?

**Comment by dweng0** [comment]
Do you have any more information?

If you  mean the initial shortcode on the md file `{{< react MyComponent >}}`

There is no way to do that as it's your entry component. You could access environment variables, or fetch the required data once inside the component.

However if you're asking about prop drilling: Passing props down to sub components is the same as in any react application:

``` jsx
import RandomWordsComponent from "./RandomWordsComponent";

function MyNestedComponent() {
    return (
      <div>
        <RandomWordsComponent someProp={true}/>
      </div>
    );
  }

export default MyNestedComponent
```

Then you can access it as you would normally
