### ISSUE TITLE
Does qreacto allow for npm packages to be imported?

### ISSUE THREAD

**Issue by HaimarR** [clearmatics/qreacto#21]
I'm trying to create a React component which requires an npm package. Is this supported by qreacto? If so, how would I proceed?

**Comment by dweng0** [comment]
Hey, yes but the packages have to be ESMs. the best place to find esms is [esm.run](https://www.jsdelivr.com/esm), search for your package in there. it can then be imported and used directly. check out the examples for way to achieve that!

The caveat here is that non ESM packages cannot be compiled "in browser" and as a result are unsupported.
